<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blocked Website</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            text-align: center;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
            padding: 30px;
            width: 300px;
        }

        h1 {
            font-size: 24px;
            color: #ff4d4d;
        }

        p {
            font-size: 16px;
            color: #555;
            margin-top: 10px;
        }

        .lock {
            font-size: 50px;
            color: #ff4d4d;
        }

        .message {
            margin-top: 20px;
            font-size: 18px;
            color: #333;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="lock">🔒</div>
        <h1>This website was blocked</h1>
        <p>Access to this site has been restricted by your school.</p>
        <div class="message">
            <p>Contact your administrator for more info.</p>
        </div>
    </div>

</body>
</html>
